### ISSUE TITLE
CatalogCopy better named to CatalogRef?

### ISSUE THREAD

**Issue by rainwoodman** [bccp/nbodykit#377] opened 2017-08-25 22:51 UTC

**Comment by nickhand** [comment] 2017-08-31 15:31
Yes, I think I like this name better...

**Comment by nickhand** [comment] 2017-09-08 19:15
The problem is that it's not always a subset, like when we are concatenating multiple source together. It's really just a Catalog where the columns are passed in as kwargs

**Comment by rainwoodman** [comment] 2017-09-08 19:21
Maybe we don't need a new class? It's just a special method of Catalog?

**Comment by rainwoodman** [comment] 2017-09-08 19:22
I am also a bit unsure the relation between this and an ArrayCatalog, which takes an dictionary as an input but does a bunch more (seemingly unnecessary) work.

**Comment by nickhand** [comment] 2017-09-08 22:00
I think the difference is that the size is known beforehand for CatalogCopy/Ref but not for ArrayCatalog . But we could remove CatalogCopy in favor of a class method of CatalogSource -- it makes more sense to have "CatalogSource" then showing up in all of the log statements

**Comment by nickhand** [comment] 2017-09-09 16:59
I guess we'll need to get rid of the abstract property tag on ``size`` for this to work?

**Comment by rainwoodman** [comment] 2017-09-09 18:08
Yes - I did that in #390.

**Comment by nickhand** [comment] 2017-09-11 15:47
closed via #390

**Closed by nickhand** 2017-09-11 15:47 UTC
