### ISSUE TITLE
nbodykit on Google Colab

### ISSUE THREAD

**Issue by margiofabiolad** [bccp/nbodykit#647] opened 2020-12-20 03:39 UTC
I'm working with Google Colab because my machine has few RAM and Hard Disc. I want to install **nbodykit** to Colab but it show me some errors: 

ERROR: Failed building wheel for Corrfunc 
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ikle2x75/Corrfunc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ikle2x75/Corrfunc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6q60m7oy/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

I used this commands: 

$ pip install numpy cython mpi4py

after, 

$ pip install nbodykit[extras]

these are the commands for Linux. 

I already have installed nbodykit but from Anaconda Distribution. But I think that it's independent of Google Colab. 

I need help! Thanks.

**Comment by rainwoodman** [comment] 2020-12-21 19:40
We never tried installing nbodykit on Google's Colab.
From the error message, looks like it is related to Corrfunc building on the colab sandbox.

Would it be possible for you to find the log files for the full command output (as instructed in the error message).

Also try to install corrfunc alone:
```
pip install corrfunc
```

I am tagging @manodeep and @lgarrison to see if they have run into similar issues.

It would be very nice we plumb through the steps of using nbodykit (and other cosmology python packages) in colab.
To make it easier for us to reproduce this error, is this a vanilla colab instance, or do you need other special steps to set up the colab environment?

**Comment by lgarrison** [comment] 2020-12-21 20:15
Just tested it; it's missing GSL.

@margiofabiolad: please run `!apt install libgsl-dev` as the first cell in the notebook.  Then try to install nbodykit again.

**Comment by manodeep** [comment] 2020-12-22 19:09
Awesome - thanks @lgarrison

**Comment by margiofabiolad** [comment] 2020-12-22 23:55
> Just tested it; it's missing GSL.
> 
> @margiofabiolad: please run `!apt install libgsl-dev` as the first cell in the notebook. Then try to install nbodykit again.

It works, and already run. Thanks everyone!!!

**Comment by rainwoodman** [comment] 2020-12-23 00:11
Thanks for the help. I am closing the ticket.

**Closed by rainwoodman** 2020-12-23 00:11 UTC
